/* Utility Macros - TLF Shell Setup */
/* Standard reusable macros for titles, footnotes, and output */

%macro setup_titles(table_id=, table_title=, population=Safety);
  title1 "Table &table_id";
  title2 "&table_title";
  title3 "Population: &population";
  footnote1 "Source: Synthetic clinical trial data";
  footnote2 "Program generated by SAS RAG Assistant prototype";
%mend setup_titles;

%macro export_listing(data=, outfile=);
  proc export data=&data
    outfile="&outfile"
    dbms=csv
    replace;
  run;
%mend export_listing;

%macro count_by_trt(data=, classvar=, out=);
  proc freq data=&data noprint;
    tables trtp * &classvar / out=&out;
  run;
%mend count_by_trt;
